version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: monitor
      POSTGRES_PASSWORD: monitorpass
      POSTGRES_DB: monitor_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./deployment/docker
      dockerfile: Dockerfile.backend
    env_file: .env
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./deployment/docker
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  db-data:
