[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip setuptools wheel",
  "cd backend && python3 -m pip install -r requirements.txt"
]

[start]
cmd = "cd backend && python3 -m gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 app:app"
