
[project]
name = "ai-infrastructure-monitoring"
[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "cd backend && python3 -m gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 app:app"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
